#---------------------------------------------------------------------
# GitHub Action Workflow
#
# Version      Date        Info
# 1.0          2020        Education Version
#
# Made by Savinov Vladimir pelephant Copyleft (c) 2020
#---------------------------------------------------------------------

name: my-github-actions
env:
  APPLICATION_NAME    : "ping-pong"
  DEPLOY_PACKAGE_NAME : "ping-pong-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  make-war:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1
      - name: set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Docker images 1
        run: docker images
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: pelephant/ping-pong:${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Docker images 2
        run: docker images